DROP TABLE IF EXISTS public.players CASCADE;

CREATE TABLE public.players (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  player_id INTEGER UNIQUE NOT NULL,
  name TEXT NOT NULL,
  team TEXT NOT NULL,
  role TEXT NOT NULL,
  base_price INTEGER NOT NULL,
  avatar_initials TEXT NOT NULL,
  country TEXT DEFAULT 'India',
  city TEXT DEFAULT 'Unknown',
  batting_style TEXT DEFAULT 'Right Handed Bat',
  bowling_style TEXT DEFAULT 'Right-arm medium',
  image_url TEXT,
  stats JSONB DEFAULT '{}'::jsonb
);

-- Enable RLS
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to read players
DROP POLICY IF EXISTS "Allow public read access to players" ON public.players;
CREATE POLICY "Allow public read access to players" ON public.players FOR SELECT USING (true);

-- Insert players
INSERT INTO public.players (player_id, name, team, role, base_price, avatar_initials, country, city, batting_style, bowling_style, image_url, stats) VALUES 
(1, 'Shreyas Iyer', 'PBKS', 'BATTER', 150, 'SI', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm legbreak', NULL, '{}'::jsonb),
(2, 'Prabhsimran Singh', 'PBKS', 'WICKETKEEPER', 50, 'PS', 'India', 'Punjab', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(3, 'Shashank Singh', 'PBKS', 'BATTER', 50, 'SS', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(4, 'Priyansh Arya', 'PBKS', 'BATTER', 50, 'PA', 'India', 'Punjab', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(5, 'Pyla Avinash', 'PBKS', 'BATTER', 50, 'PA', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(6, 'Harnoor Singh', 'PBKS', 'BATTER', 50, 'HS', 'India', 'Punjab', 'Left Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(7, 'Vishnu Vinod', 'PBKS', 'WICKETKEEPER', 50, 'VV', 'India', 'Punjab', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(8, 'Marcus Stoinis', 'PBKS', 'ALL-ROUNDER', 50, 'MS', 'Australia', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(9, 'Marco Jansen', 'PBKS', 'ALL-ROUNDER', 50, 'MJ', 'South Africa', 'Punjab', 'Right Handed Bat', 'Left-arm fast', NULL, '{}'::jsonb),
(10, 'Nehal Wadhera', 'PBKS', 'ALL-ROUNDER', 50, 'NW', 'India', 'Punjab', 'Left Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(11, 'Azmatullah Omarzai', 'PBKS', 'ALL-ROUNDER', 50, 'AO', 'Afghanistan', 'Punjab', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(12, 'Musheer Khan', 'PBKS', 'ALL-ROUNDER', 50, 'MK', 'India', 'Punjab', 'Right Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(13, 'Cooper Connolly', 'PBKS', 'ALL-ROUNDER', 50, 'CC', 'India', 'Punjab', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(14, 'Mitchell Owen', 'PBKS', 'ALL-ROUNDER', 50, 'MO', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(15, 'Arshdeep Singh', 'PBKS', 'BOWLER', 50, 'AS', 'India', 'Punjab', 'Left Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(16, 'Yuzvendra Chahal', 'PBKS', 'BOWLER', 50, 'YC', 'India', 'Punjab', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(17, 'Lockie Ferguson', 'PBKS', 'BOWLER', 50, 'LF', 'New Zealand', 'Punjab', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(18, 'Harpreet Brar', 'PBKS', 'BOWLER', 50, 'HB', 'India', 'Punjab', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(19, 'Xavier Bartlett', 'PBKS', 'BOWLER', 50, 'XB', 'Australia', 'Punjab', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(20, 'Yash Thakur', 'PBKS', 'BOWLER', 50, 'YT', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(21, 'Vijaykumar Vyshak', 'PBKS', 'BOWLER', 50, 'VV', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(22, 'Pravin Dubey', 'PBKS', 'BOWLER', 50, 'PD', 'India', 'Punjab', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(23, 'Ben Dwarshuis', 'PBKS', 'BOWLER', 50, 'BD', 'Australia', 'Punjab', 'Left Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(24, 'Suryansh Shedge', 'PBKS', 'BOWLER', 50, 'SS', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(25, 'Vishal Nishad', 'PBKS', 'BOWLER', 50, 'VN', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(26, 'Dhruv Jurel', 'RR', 'WICKETKEEPER', 50, 'DJ', 'India', 'Rajasthan', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(27, 'Donovan Ferreira', 'RR', 'WICKETKEEPER', 50, 'DF', 'South Africa', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(28, 'Lhuan-dre Pretorius', 'RR', 'WICKETKEEPER', 50, 'LP', 'India', 'Rajasthan', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(29, 'Ravi Singh', 'RR', 'WICKETKEEPER', 50, 'RS', 'India', 'Rajasthan', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(30, 'Yashasvi Jaiswal', 'RR', 'BATTER', 50, 'YJ', 'India', 'Rajasthan', 'Left Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(31, 'Shimron Hetmyer', 'RR', 'BATTER', 50, 'SH', 'West Indies', 'Rajasthan', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(32, 'Shubham Dubey', 'RR', 'BATTER', 50, 'SD', 'India', 'Rajasthan', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(33, 'Vaibhav Sooryavanshi', 'RR', 'BATTER', 50, 'VS', 'India', 'Rajasthan', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(34, 'Aman Perala', 'RR', 'BATTER', 50, 'AP', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(35, 'Ravindra Jadeja', 'RR', 'ALL-ROUNDER', 50, 'RJ', 'India', 'Rajasthan', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(36, 'Riyan Parag', 'RR', 'ALL-ROUNDER', 50, 'RP', 'India', 'Rajasthan', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(37, 'Yudhvir Singh', 'RR', 'ALL-ROUNDER', 50, 'YS', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(38, 'Dasun Shanaka', 'RR', 'ALL-ROUNDER', 50, 'DS', 'Sri Lanka', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(39, 'Vignesh Puthur', 'RR', 'ALL-ROUNDER', 50, 'VP', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(40, 'Brijesh Sharma', 'RR', 'ALL-ROUNDER', 50, 'BS', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(41, 'Yash Punja', 'RR', 'ALL-ROUNDER', 50, 'YP', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(42, 'Riyan Parag', 'RR', 'ALL-ROUNDER', 50, 'RP', 'India', 'Rajasthan', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(43, 'Jofra Archer', 'RR', 'BOWLER', 50, 'JA', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(44, 'Sandeep Sharma', 'RR', 'BOWLER', 50, 'SS', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(45, 'Ravi Bishnoi', 'RR', 'BOWLER', 50, 'RB', 'India', 'Rajasthan', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(46, 'Nandre Burger', 'RR', 'BOWLER', 50, 'NB', 'South Africa', 'Rajasthan', 'Left Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(47, 'Adam Milne', 'RR', 'BOWLER', 50, 'AM', 'New Zealand', 'Rajasthan', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(48, 'Tushar Deshpande', 'RR', 'BOWLER', 50, 'TD', 'India', 'Rajasthan', 'Left Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(49, 'Kuldeep Sen', 'RR', 'BOWLER', 50, 'KS', 'India', 'Rajasthan', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(50, 'Sushant Mishra', 'RR', 'BOWLER', 50, 'SM', 'India', 'Rajasthan', 'Left Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(51, 'Kwena Maphaka', 'RR', 'BOWLER', 50, 'KM', 'South Africa', 'Rajasthan', 'Left Handed Bat', 'Left-arm fast', NULL, '{}'::jsonb),
(52, 'Rajat Patidar', 'RCB', 'BATTER', 50, 'RP', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(53, 'Virat Kohli', 'RCB', 'BATTER', 200, 'VK', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(54, 'Devdutt Padikkal', 'RCB', 'BATTER', 50, 'DP', 'India', 'Bengaluru', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(55, 'Phil Salt', 'RCB', 'WICKETKEEPER', 50, 'PS', 'England', 'Bengaluru', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(56, 'Jitesh Sharma', 'RCB', 'WICKETKEEPER', 50, 'JS', 'India', 'Bengaluru', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(57, 'Jordan Cox', 'RCB', 'WICKETKEEPER', 50, 'JC', 'India', 'Bengaluru', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(58, 'Krunal Pandya', 'RCB', 'ALL-ROUNDER', 50, 'KP', 'India', 'Bengaluru', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(59, 'Tim David', 'RCB', 'ALL-ROUNDER', 50, 'TD', 'Australia', 'Bengaluru', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(60, 'Romario Shepherd', 'RCB', 'ALL-ROUNDER', 50, 'RS', 'West Indies', 'Bengaluru', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(61, 'Jacob Bethell', 'RCB', 'ALL-ROUNDER', 50, 'JB', 'India', 'Bengaluru', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(62, 'Venkatesh Iyer', 'RCB', 'ALL-ROUNDER', 50, 'VI', 'India', 'Bengaluru', 'Left Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(63, 'Swapnil Singh', 'RCB', 'ALL-ROUNDER', 50, 'SS', 'India', 'Bengaluru', 'Right Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(64, 'Vihaan Malhotra', 'RCB', 'ALL-ROUNDER', 50, 'VM', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(65, 'Bhuvneshwar Kumar', 'RCB', 'BOWLER', 50, 'BK', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(66, 'Josh Hazlewood', 'RCB', 'BOWLER', 50, 'JH', 'Australia', 'Bengaluru', 'Left Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(67, 'Yash Dayal', 'RCB', 'BOWLER', 50, 'YD', 'India', 'Bengaluru', 'Right Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(68, 'Nuwan Thushara', 'RCB', 'BOWLER', 50, 'NT', 'Sri Lanka', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(69, 'Suyash Sharma', 'RCB', 'BOWLER', 50, 'SS', 'India', 'Bengaluru', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(70, 'Jacob Duffy', 'RCB', 'BOWLER', 50, 'JD', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(71, 'Rasikh Salam', 'RCB', 'BOWLER', 50, 'RS', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(72, 'Abhinandan Singh', 'RCB', 'BOWLER', 50, 'AS', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(73, 'Satvik Deswal', 'RCB', 'BOWLER', 50, 'SD', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(74, 'Vicky Ostwal', 'RCB', 'BOWLER', 50, 'VO', 'India', 'Bengaluru', 'Right Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(75, 'Mangesh Yadav', 'RCB', 'BOWLER', 50, 'MY', 'India', 'Bengaluru', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(76, 'Ruturaj Gaikwad', 'CSK', 'BATTER', 150, 'RG', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(77, 'Dewald Brevis', 'CSK', 'BATTER', 50, 'DB', 'South Africa', 'Chennai', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(78, 'Sarfaraz Khan', 'CSK', 'BATTER', 50, 'SK', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(79, 'Kartik Sharma', 'CSK', 'WICKETKEEPER', 50, 'KS', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(80, 'MS Dhoni', 'CSK', 'WICKETKEEPER', 200, 'MD', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(81, 'Sanju Samson', 'CSK', 'WICKETKEEPER', 150, 'SS', 'India', 'Chennai', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(82, 'Urvil Patel', 'CSK', 'WICKETKEEPER', 50, 'UP', 'India', 'Chennai', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(83, 'Shivam Dube', 'CSK', 'ALL-ROUNDER', 50, 'SD', 'India', 'Chennai', 'Left Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(84, 'Jamie Overton', 'CSK', 'ALL-ROUNDER', 50, 'JO', 'England', 'Chennai', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(85, 'Matthew Short', 'CSK', 'ALL-ROUNDER', 50, 'MS', 'Australia', 'Chennai', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(86, 'Aman Khan', 'CSK', 'ALL-ROUNDER', 50, 'AK', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(87, 'Ramakrishna Ghosh', 'CSK', 'ALL-ROUNDER', 50, 'RG', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(88, 'Prashant Veer', 'CSK', 'ALL-ROUNDER', 50, 'PV', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(89, 'Zakary Foulkes', 'CSK', 'ALL-ROUNDER', 50, 'ZF', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(90, 'Noor Ahmad', 'CSK', 'BOWLER', 50, 'NA', 'Afghanistan', 'Chennai', 'Right Handed Bat', 'Left-arm wrist-spin', NULL, '{}'::jsonb),
(91, 'Khaleel Ahmed', 'CSK', 'BOWLER', 50, 'KA', 'India', 'Chennai', 'Right Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(92, 'Anshul Kamboj', 'CSK', 'BOWLER', 50, 'AK', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(93, 'Mukesh Choudhary', 'CSK', 'BOWLER', 50, 'MC', 'India', 'Chennai', 'Left Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(94, 'Shreyas Gopal', 'CSK', 'BOWLER', 50, 'SG', 'India', 'Chennai', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(95, 'Gurjapneet Singh', 'CSK', 'BOWLER', 50, 'GS', 'India', 'Chennai', 'Right Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(96, 'Akeal Hosein', 'CSK', 'BOWLER', 50, 'AH', 'West Indies', 'Chennai', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(97, 'Matt Henry', 'CSK', 'BOWLER', 50, 'MH', 'New Zealand', 'Chennai', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(98, 'Rahul Chahar', 'CSK', 'BOWLER', 50, 'RC', 'India', 'Chennai', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(99, 'Spencer Johnson', 'CSK', 'BOWLER', 50, 'SJ', 'Australia', 'Chennai', 'Left Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(100, 'Akash Madhwal', 'CSK', 'BOWLER', 50, 'AM', 'India', 'Chennai', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(101, 'Heinrich Klaasen', 'SRH', 'WICKETKEEPER', 50, 'HK', 'South Africa', 'Hyderabad', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(102, 'Ishan Kishan', 'SRH', 'WICKETKEEPER', 50, 'IK', 'India', 'Hyderabad', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(103, 'Salil Arora', 'SRH', 'WICKETKEEPER', 50, 'SA', 'India', 'Hyderabad', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(104, 'Travis Head', 'SRH', 'BATTER', 50, 'TH', 'Australia', 'Hyderabad', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(105, 'Aniket Verma', 'SRH', 'BATTER', 50, 'AV', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(106, 'Smaran Ravichandran', 'SRH', 'BATTER', 50, 'SR', 'India', 'Hyderabad', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(107, 'Abhishek Sharma', 'SRH', 'ALL-ROUNDER', 50, 'AS', 'India', 'Hyderabad', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(108, 'Nitish Kumar Reddy', 'SRH', 'ALL-ROUNDER', 50, 'NR', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(109, 'Liam Livingstone', 'SRH', 'ALL-ROUNDER', 50, 'LL', 'England', 'Hyderabad', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(110, 'Kamindu Mendis', 'SRH', 'ALL-ROUNDER', 50, 'KM', 'Sri Lanka', 'Hyderabad', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(111, 'Harsh Dubey', 'SRH', 'ALL-ROUNDER', 50, 'HD', 'India', 'Hyderabad', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(112, 'Amit Kumar', 'SRH', 'ALL-ROUNDER', 50, 'AK', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(113, 'Pat Cummins', 'SRH', 'BOWLER', 200, 'PC', 'Australia', 'Hyderabad', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(114, 'Harshal Patel', 'SRH', 'BOWLER', 50, 'HP', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(115, 'Eshan Malinga', 'SRH', 'BOWLER', 50, 'EM', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(116, 'Jaydev Unadkat', 'SRH', 'BOWLER', 50, 'JU', 'India', 'Hyderabad', 'Right Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(117, 'Shivam Mavi', 'SRH', 'BOWLER', 50, 'SM', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(118, 'Zeeshan Ansari', 'SRH', 'BOWLER', 50, 'ZA', 'India', 'Hyderabad', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(119, 'Praful Hinge', 'SRH', 'BOWLER', 50, 'PH', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(120, 'Sakib Hussain', 'SRH', 'BOWLER', 50, 'SH', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(121, 'Krains Fuletra', 'SRH', 'BOWLER', 50, 'KF', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(122, 'Onkar Tarmale', 'SRH', 'BOWLER', 50, 'OT', 'India', 'Hyderabad', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(123, 'Shubman Gill', 'GT', 'BATTER', 150, 'SG', 'India', 'Gujarat', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(124, 'Jos Buttler', 'GT', 'WICKETKEEPER', 50, 'JB', 'England', 'Gujarat', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(125, 'Sai Sudharsan', 'GT', 'BATTER', 50, 'SS', 'India', 'Gujarat', 'Left Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(126, 'Shahrukh Khan', 'GT', 'BATTER', 50, 'SK', 'India', 'Gujarat', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(127, 'Kumar Kushagra', 'GT', 'WICKETKEEPER', 50, 'KK', 'India', 'Gujarat', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(128, 'Anuj Rawat', 'GT', 'WICKETKEEPER', 50, 'AR', 'India', 'Gujarat', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(129, 'Tom Banton', 'GT', 'WICKETKEEPER', 50, 'TB', 'England', 'Gujarat', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(130, 'Glenn Phillips', 'GT', 'BATTER', 50, 'GP', 'New Zealand', 'Gujarat', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(131, 'Rashid Khan', 'GT', 'ALL-ROUNDER', 200, 'RK', 'Afghanistan', 'Gujarat', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(132, 'Washington Sundar', 'GT', 'ALL-ROUNDER', 50, 'WS', 'India', 'Gujarat', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(133, 'Rahul Tewatia', 'GT', 'ALL-ROUNDER', 50, 'RT', 'India', 'Gujarat', 'Left Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(134, 'Jason Holder', 'GT', 'ALL-ROUNDER', 50, 'JH', 'West Indies', 'Gujarat', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(135, 'Nishant Sindhu', 'GT', 'ALL-ROUNDER', 50, 'NS', 'India', 'Gujarat', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(136, 'Manav Suthar', 'GT', 'ALL-ROUNDER', 50, 'MS', 'India', 'Gujarat', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(137, 'Sai Kishore', 'GT', 'ALL-ROUNDER', 50, 'SK', 'India', 'Gujarat', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(138, 'Mohammed Siraj', 'GT', 'BOWLER', 50, 'MS', 'India', 'Gujarat', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(139, 'Kagiso Rabada', 'GT', 'BOWLER', 50, 'KR', 'South Africa', 'Gujarat', 'Left Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(140, 'Prasidh Krishna', 'GT', 'BOWLER', 50, 'PK', 'India', 'Gujarat', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(141, 'Ishant Sharma', 'GT', 'BOWLER', 50, 'IS', 'India', 'Gujarat', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(142, 'Arshad Khan', 'GT', 'BOWLER', 50, 'AK', 'India', 'Gujarat', 'Left Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(143, 'Gurnoor Brar', 'GT', 'BOWLER', 50, 'GB', 'India', 'Gujarat', 'Left Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(144, 'Ashok Sharma', 'GT', 'BOWLER', 50, 'AS', 'India', 'Gujarat', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(145, 'Luke Wood', 'GT', 'BOWLER', 50, 'LW', 'England', 'Gujarat', 'Left Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(146, 'Prithvi Raj Yarra', 'GT', 'BOWLER', 50, 'PY', 'India', 'Gujarat', 'Right Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(147, 'Rishabh Pant', 'LSG', 'WICKETKEEPER', 150, 'RP', 'India', 'Lucknow', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(148, 'Nicholas Pooran', 'LSG', 'WICKETKEEPER', 50, 'NP', 'West Indies', 'Lucknow', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(149, 'Josh Inglis', 'LSG', 'WICKETKEEPER', 50, 'JI', 'Australia', 'Lucknow', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(150, 'Mukul Choudhary', 'LSG', 'WICKETKEEPER', 50, 'MC', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(151, 'Aiden Markram', 'LSG', 'BATTER', 50, 'AM', 'South Africa', 'Lucknow', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(152, 'Ayush Badoni', 'LSG', 'BATTER', 50, 'AB', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(153, 'Abdul Samad', 'LSG', 'BATTER', 50, 'AS', 'India', 'Lucknow', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(154, 'Matthew Breetzke', 'LSG', 'WICKETKEEPER', 50, 'MB', 'South Africa', 'Lucknow', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(155, 'Himmat Singh', 'LSG', 'BATTER', 50, 'HS', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(156, 'Akshat Raghuwanshi', 'LSG', 'BATTER', 50, 'AR', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(157, 'Mitchell Marsh', 'LSG', 'ALL-ROUNDER', 50, 'MM', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(158, 'Shahbaz Ahamad', 'LSG', 'ALL-ROUNDER', 50, 'SA', 'India', 'Lucknow', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(159, 'Arshin Kulkarni', 'LSG', 'ALL-ROUNDER', 50, 'AK', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(160, 'George Linde', 'LSG', 'ALL-ROUNDER', 50, 'GL', 'South Africa', 'Lucknow', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(161, 'Mohammed Shami', 'LSG', 'BOWLER', 50, 'MS', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(162, 'Mayank Yadav', 'LSG', 'BOWLER', 50, 'MY', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(163, 'Avesh Khan', 'LSG', 'BOWLER', 50, 'AK', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(164, 'Mohsin Khan', 'LSG', 'BOWLER', 50, 'MK', 'India', 'Lucknow', 'Left Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(165, 'Arjun Tendulkar', 'LSG', 'BOWLER', 50, 'AT', 'India', 'Lucknow', 'Left Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(166, 'Manimaran Siddharth', 'LSG', 'BOWLER', 50, 'MS', 'India', 'Lucknow', 'Right Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(167, 'Prince Yadav', 'LSG', 'BOWLER', 50, 'PY', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(168, 'Anrich Nortje', 'LSG', 'BOWLER', 50, 'AN', 'South Africa', 'Lucknow', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(169, 'Akash Singh', 'LSG', 'BOWLER', 50, 'AS', 'India', 'Lucknow', 'Right Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(170, 'Digvesh Singh Rathi', 'LSG', 'BOWLER', 50, 'DR', 'India', 'Lucknow', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(171, 'Naman Tiwari', 'LSG', 'BOWLER', 50, 'NT', 'India', 'Lucknow', 'Left Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(172, 'KL Rahul', 'DC', 'WICKETKEEPER', 200, 'KR', 'India', 'Delhi', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(173, 'Tristan Stubbs', 'DC', 'WICKETKEEPER', 50, 'TS', 'South Africa', 'Delhi', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(174, 'Abishek Porel', 'DC', 'WICKETKEEPER', 50, 'AP', 'India', 'Delhi', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(175, 'Ben Duckett', 'DC', 'BATTER', 50, 'BD', 'England', 'Delhi', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(176, 'David Miller', 'DC', 'BATTER', 50, 'DM', 'South Africa', 'Delhi', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(177, 'Pathum Nissanka', 'DC', 'BATTER', 50, 'PN', 'Sri Lanka', 'Delhi', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(178, 'Prithvi Shaw', 'DC', 'BATTER', 50, 'PS', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(179, 'Karun Nair', 'DC', 'BATTER', 50, 'KN', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(180, 'Nitish Rana', 'DC', 'BATTER', 50, 'NR', 'India', 'Delhi', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(181, 'Sahil Parakh', 'DC', 'BATTER', 50, 'SP', 'India', 'Delhi', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(182, 'Axar Patel', 'DC', 'ALL-ROUNDER', 50, 'AP', 'India', 'Delhi', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(183, 'Sameer Rizvi', 'DC', 'ALL-ROUNDER', 50, 'SR', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(184, 'Ashutosh Sharma', 'DC', 'ALL-ROUNDER', 50, 'AS', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(185, 'Ajay Mandal', 'DC', 'ALL-ROUNDER', 50, 'AM', 'India', 'Delhi', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(186, 'Kuldeep Yadav', 'DC', 'BOWLER', 50, 'KY', 'India', 'Delhi', 'Left Handed Bat', 'Left-arm wrist-spin', NULL, '{}'::jsonb),
(187, 'Mitchell Starc', 'DC', 'BOWLER', 150, 'MS', 'Australia', 'Delhi', 'Left Handed Bat', 'Left-arm fast', NULL, '{}'::jsonb),
(188, 'T Natarajan', 'DC', 'BOWLER', 50, 'TN', 'India', 'Delhi', 'Left Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(189, 'Mukesh Kumar', 'DC', 'BOWLER', 50, 'MK', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(190, 'Dushmantha Chameera', 'DC', 'BOWLER', 50, 'DC', 'Sri Lanka', 'Delhi', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(191, 'Lungi Ngidi', 'DC', 'BOWLER', 50, 'LN', 'South Africa', 'Delhi', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(192, 'Kyle Jamieson', 'DC', 'BOWLER', 50, 'KJ', 'New Zealand', 'Delhi', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(193, 'Vipraj Nigam', 'DC', 'BOWLER', 50, 'VN', 'India', 'Delhi', 'Right Handed Bat', 'Legbreak', NULL, '{}'::jsonb),
(194, 'Auqib Nabi Dar', 'DC', 'BOWLER', 50, 'AD', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(195, 'Tripurana Vijay', 'DC', 'BOWLER', 50, 'TV', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(196, 'Madhav Tiwari', 'DC', 'BOWLER', 50, 'MT', 'India', 'Delhi', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(197, 'Tim Seifert', 'KKR', 'WICKETKEEPER', 50, 'TS', 'New Zealand', 'Kolkata', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(198, 'Tejasvi Singh', 'KKR', 'WICKETKEEPER', 50, 'TS', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(199, 'Rinku Singh', 'KKR', 'BATTER', 50, 'RS', 'India', 'Kolkata', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(200, 'Manish Pandey', 'KKR', 'BATTER', 50, 'MP', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(201, 'Rovman Powell', 'KKR', 'BATTER', 50, 'RP', 'West Indies', 'Kolkata', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(202, 'Rahul Tripathi', 'KKR', 'BATTER', 50, 'RT', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(203, 'Finn Allen', 'KKR', 'BATTER', 50, 'FA', 'New Zealand', 'Kolkata', 'Right Handed Bat', 'None', NULL, '{}'::jsonb),
(204, 'Sarthak Ranjan', 'KKR', 'BATTER', 50, 'SR', 'India', 'Kolkata', 'Left Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(205, 'Angkrish Raghuvanshi', 'KKR', 'BATTER', 50, 'AR', 'India', 'Kolkata', 'Right Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(206, 'Ajinkya Rahane', 'KKR', 'BATTER', 50, 'AR', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(207, 'Sunil Narine', 'KKR', 'ALL-ROUNDER', 50, 'SN', 'West Indies', 'Kolkata', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(208, 'Cameron Green', 'KKR', 'ALL-ROUNDER', 50, 'CG', 'Australia', 'Kolkata', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(209, 'Rachin Ravindra', 'KKR', 'ALL-ROUNDER', 50, 'RR', 'New Zealand', 'Kolkata', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(210, 'Ramandeep Singh', 'KKR', 'ALL-ROUNDER', 50, 'RS', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(211, 'Anukul Roy', 'KKR', 'ALL-ROUNDER', 50, 'AR', 'India', 'Kolkata', 'Left Handed Bat', 'Slow left-arm orthodox', NULL, '{}'::jsonb),
(212, 'Daksh Kamra', 'KKR', 'ALL-ROUNDER', 50, 'DK', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(213, 'Varun Chakaravarthy', 'KKR', 'BOWLER', 50, 'VC', 'India', 'Kolkata', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(214, 'Harshit Rana', 'KKR', 'BOWLER', 50, 'HR', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(215, 'Vaibhav Arora', 'KKR', 'BOWLER', 50, 'VA', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm medium-fast', NULL, '{}'::jsonb),
(216, 'Matheesha Pathirana', 'KKR', 'BOWLER', 50, 'MP', 'Sri Lanka', 'Kolkata', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(217, 'Umran Malik', 'KKR', 'BOWLER', 50, 'UM', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(218, 'Blessing Muzarabani', 'KKR', 'BOWLER', 50, 'BM', 'Zimbabwe', 'Kolkata', 'Right Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(219, 'Kartik Tyagi', 'KKR', 'BOWLER', 50, 'KT', 'India', 'Kolkata', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(220, 'Prashant Solanki', 'KKR', 'BOWLER', 50, 'PS', 'India', 'Kolkata', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(221, 'Saurabh Dubey', 'KKR', 'BOWLER', 50, 'SD', 'India', 'Kolkata', 'Right Handed Bat', 'Left-arm medium-fast', NULL, '{}'::jsonb),
(222, 'Rohit Sharma', 'MI', 'BATTER', 50, 'RS', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(223, 'Surya Kumar Yadav', 'MI', 'BATTER', 50, 'SY', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(224, 'Robin Minz', 'MI', 'WICKETKEEPER', 50, 'RM', 'India', 'Mumbai', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(225, 'Ryan Rickelton', 'MI', 'WICKETKEEPER', 50, 'RR', 'South Africa', 'Mumbai', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(226, 'Tilak Varma', 'MI', 'BATTER', 50, 'TV', 'India', 'Mumbai', 'Left Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(227, 'Trent Boult', 'MI', 'BOWLER', 50, 'TB', 'New Zealand', 'Mumbai', 'Right Handed Bat', 'Left-arm fast-medium', NULL, '{}'::jsonb),
(228, 'Jasprit Bumrah', 'MI', 'BOWLER', 50, 'JB', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm fast', NULL, '{}'::jsonb),
(229, 'Deepak Chahar', 'MI', 'BOWLER', 50, 'DC', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(230, 'Ashwani Kumar', 'MI', 'BOWLER', 50, 'AK', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(231, 'Raghu Sharma', 'MI', 'BOWLER', 50, 'RS', 'India', 'Mumbai', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(232, 'Allah Ghazanfar', 'MI', 'BOWLER', 50, 'AG', 'Afghanistan', 'Mumbai', 'Right Handed Bat', 'Right-arm offbreak', NULL, '{}'::jsonb),
(233, 'Mayank Markande', 'MI', 'BOWLER', 50, 'MM', 'India', 'Mumbai', 'Right Handed Bat', 'Legbreak googly', NULL, '{}'::jsonb),
(234, 'Sherfane Rutherford', 'MI', 'BATTER', 50, 'SR', 'West Indies', 'Mumbai', 'Left Handed Bat', 'Right-arm fast-medium', NULL, '{}'::jsonb),
(235, 'Quinton De Kock', 'MI', 'WICKETKEEPER', 50, 'QK', 'South Africa', 'Mumbai', 'Left Handed Bat', 'None', NULL, '{}'::jsonb),
(236, 'Krish Bhagat', 'MI', 'BOWLER', 50, 'KB', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(237, 'Mohammad Izhar', 'MI', 'BOWLER', 50, 'MI', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb),
(238, 'Danish Malewar', 'MI', 'BATTER', 50, 'DM', 'India', 'Mumbai', 'Right Handed Bat', 'Right-arm medium', NULL, '{}'::jsonb);
