import re

data = {
    'Shreyas Iyer': ('Right Handed Bat', 'Right-arm legbreak'),
    'Prabhsimran Singh': ('Right Handed Bat', 'None'),
    'Shashank Singh': ('Right Handed Bat', 'Right-arm medium'),
    'Priyansh Arya': ('Left Handed Bat', 'None'),
    'Pyla Avinash': ('Right Handed Bat', 'Right-arm medium'),
    'Harnoor Singh': ('Left Handed Bat', 'Right-arm medium'),
    'Vishnu Vinod': ('Right Handed Bat', 'None'),
    'Marcus Stoinis': ('Right Handed Bat', 'Right-arm medium'),
    'Marco Jansen': ('Right Handed Bat', 'Left-arm fast'),
    'Nehal Wadhera': ('Left Handed Bat', 'Legbreak'),
    'Azmatullah Omarzai': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Musheer Khan': ('Right Handed Bat', 'Slow left-arm orthodox'),
    'Cooper Connolly': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Mitchell Owen': ('Right Handed Bat', 'Right-arm medium'),
    'Arshdeep Singh': ('Left Handed Bat', 'Left-arm medium-fast'),
    'Yuzvendra Chahal': ('Right Handed Bat', 'Legbreak googly'),
    'Lockie Ferguson': ('Right Handed Bat', 'Right-arm fast'),
    'Harpreet Brar': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Xavier Bartlett': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Yash Thakur': ('Right Handed Bat', 'Right-arm medium'),
    'Vijaykumar Vyshak': ('Right Handed Bat', 'Right-arm medium'),
    'Pravin Dubey': ('Right Handed Bat', 'Legbreak googly'),
    'Ben Dwarshuis': ('Left Handed Bat', 'Left-arm fast-medium'),
    'Suryansh Shedge': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Vishal Nishad': ('Right Handed Bat', 'Right-arm medium'),
    'Dhruv Jurel': ('Right Handed Bat', 'None'),
    'Donovan Ferreira': ('Right Handed Bat', 'Right-arm medium'),
    'Lhuan-dre Pretorius': ('Left Handed Bat', 'None'),
    'Ravi Singh': ('Right Handed Bat', 'None'),
    'Yashasvi Jaiswal': ('Left Handed Bat', 'Legbreak'),
    'Shimron Hetmyer': ('Left Handed Bat', 'None'),
    'Shubham Dubey': ('Left Handed Bat', 'Right-arm offbreak'),
    'Vaibhav Sooryavanshi': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Aman Perala': ('Right Handed Bat', 'Right-arm offbreak'),
    'Ravindra Jadeja': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Riyan Parag': ('Right Handed Bat', 'Legbreak'),
    'Yudhvir Singh': ('Right Handed Bat', 'Right-arm medium'),
    'Dasun Shanaka': ('Right Handed Bat', 'Right-arm medium'),
    'Vignesh Puthur': ('Right Handed Bat', 'Right-arm medium'),
    'Brijesh Sharma': ('Right Handed Bat', 'Right-arm medium'),
    'Yash Punja': ('Right Handed Bat', 'Right-arm medium'),
    'Jofra Archer': ('Right Handed Bat', 'Right-arm fast'),
    'Sandeep Sharma': ('Right Handed Bat', 'Right-arm medium'),
    'Ravi Bishnoi': ('Right Handed Bat', 'Legbreak googly'),
    'Nandre Burger': ('Left Handed Bat', 'Left-arm fast-medium'),
    'Adam Milne': ('Right Handed Bat', 'Right-arm fast'),
    'Tushar Deshpande': ('Left Handed Bat', 'Right-arm medium'),
    'Kuldeep Sen': ('Right Handed Bat', 'Right-arm fast'),
    'Sushant Mishra': ('Left Handed Bat', 'Left-arm fast-medium'),
    'Kwena Maphaka': ('Left Handed Bat', 'Left-arm fast'),
    'Rajat Patidar': ('Right Handed Bat', 'Right-arm offbreak'),
    'Virat Kohli': ('Right Handed Bat', 'Right-arm medium'),
    'Devdutt Padikkal': ('Left Handed Bat', 'Right-arm offbreak'),
    'Phil Salt': ('Right Handed Bat', 'None'),
    'Jitesh Sharma': ('Right Handed Bat', 'None'),
    'Jordan Cox': ('Right Handed Bat', 'None'),
    'Krunal Pandya': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Tim David': ('Right Handed Bat', 'Right-arm offbreak'),
    'Romario Shepherd': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Jacob Bethell': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Venkatesh Iyer': ('Left Handed Bat', 'Right-arm medium'),
    'Swapnil Singh': ('Right Handed Bat', 'Slow left-arm orthodox'),
    'Vihaan Malhotra': ('Right Handed Bat', 'Right-arm medium'),
    'Bhuvneshwar Kumar': ('Right Handed Bat', 'Right-arm medium'),
    'Josh Hazlewood': ('Left Handed Bat', 'Right-arm fast-medium'),
    'Yash Dayal': ('Right Handed Bat', 'Left-arm fast-medium'),
    'Nuwan Thushara': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Suyash Sharma': ('Right Handed Bat', 'Legbreak googly'),
    'Jacob Duffy': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Rasikh Salam': ('Right Handed Bat', 'Right-arm medium'),
    'Abhinandan Singh': ('Right Handed Bat', 'Right-arm medium'),
    'Satvik Deswal': ('Right Handed Bat', 'Right-arm medium'),
    'Vicky Ostwal': ('Right Handed Bat', 'Slow left-arm orthodox'),
    'Mangesh Yadav': ('Right Handed Bat', 'Right-arm medium'),
    'Ruturaj Gaikwad': ('Right Handed Bat', 'Right-arm offbreak'),
    'Dewald Brevis': ('Right Handed Bat', 'Legbreak'),
    'Sarfaraz Khan': ('Right Handed Bat', 'Right-arm offbreak'),
    'Kartik Sharma': ('Right Handed Bat', 'Right-arm medium'),
    'MS Dhoni': ('Right Handed Bat', 'Right-arm medium'),
    'Sanju Samson': ('Right Handed Bat', 'None'),
    'Urvil Patel': ('Right Handed Bat', 'None'),
    'Shivam Dube': ('Left Handed Bat', 'Right-arm medium'),
    'Jamie Overton': ('Right Handed Bat', 'Right-arm fast'),
    'Matthew Short': ('Right Handed Bat', 'Right-arm offbreak'),
    'Aman Khan': ('Right Handed Bat', 'Right-arm medium'),
    'Ramakrishna Ghosh': ('Right Handed Bat', 'Right-arm medium'),
    'Prashant Veer': ('Right Handed Bat', 'Right-arm medium'),
    'Zakary Foulkes': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Noor Ahmad': ('Right Handed Bat', 'Left-arm wrist-spin'),
    'Khaleel Ahmed': ('Right Handed Bat', 'Left-arm medium-fast'),
    'Anshul Kamboj': ('Right Handed Bat', 'Right-arm medium'),
    'Mukesh Choudhary': ('Left Handed Bat', 'Left-arm medium-fast'),
    'Shreyas Gopal': ('Right Handed Bat', 'Legbreak'),
    'Gurjapneet Singh': ('Right Handed Bat', 'Left-arm fast-medium'),
    'Akeal Hosein': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Matt Henry': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Rahul Chahar': ('Right Handed Bat', 'Legbreak googly'),
    'Spencer Johnson': ('Left Handed Bat', 'Left-arm fast-medium'),
    'Akash Madhwal': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Heinrich Klaasen': ('Right Handed Bat', 'Right-arm offbreak'),
    'Ishan Kishan': ('Left Handed Bat', 'None'),
    'Salil Arora': ('Right Handed Bat', 'None'),
    'Travis Head': ('Left Handed Bat', 'Right-arm offbreak'),
    'Aniket Verma': ('Right Handed Bat', 'Right-arm medium'),
    'Smaran Ravichandran': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Abhishek Sharma': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Nitish Kumar Reddy': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Liam Livingstone': ('Right Handed Bat', 'Legbreak'),
    'Kamindu Mendis': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Harsh Dubey': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Amit Kumar': ('Right Handed Bat', 'Right-arm medium'),
    'Pat Cummins': ('Right Handed Bat', 'Right-arm fast'),
    'Harshal Patel': ('Right Handed Bat', 'Right-arm medium'),
    'Eshan Malinga': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Jaydev Unadkat': ('Right Handed Bat', 'Left-arm medium-fast'),
    'Shivam Mavi': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Zeeshan Ansari': ('Right Handed Bat', 'Legbreak googly'),
    'Praful Hinge': ('Right Handed Bat', 'Right-arm medium'),
    'Sakib Hussain': ('Right Handed Bat', 'Right-arm medium'),
    'Krains Fuletra': ('Right Handed Bat', 'Right-arm medium'),
    'Onkar Tarmale': ('Right Handed Bat', 'Right-arm medium'),
    'Shubman Gill': ('Right Handed Bat', 'Right-arm offbreak'),
    'Jos Buttler': ('Right Handed Bat', 'None'),
    'Sai Sudharsan': ('Left Handed Bat', 'Legbreak'),
    'Shahrukh Khan': ('Right Handed Bat', 'Right-arm offbreak'),
    'Kumar Kushagra': ('Right Handed Bat', 'None'),
    'Anuj Rawat': ('Left Handed Bat', 'None'),
    'Tom Banton': ('Right Handed Bat', 'None'),
    'Glenn Phillips': ('Right Handed Bat', 'Right-arm offbreak'),
    'Rashid Khan': ('Right Handed Bat', 'Legbreak googly'),
    'Washington Sundar': ('Left Handed Bat', 'Right-arm offbreak'),
    'Rahul Tewatia': ('Left Handed Bat', 'Legbreak'),
    'Jason Holder': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Nishant Sindhu': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Manav Suthar': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Sai Kishore': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Mohammed Siraj': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Kagiso Rabada': ('Left Handed Bat', 'Right-arm fast'),
    'Prasidh Krishna': ('Right Handed Bat', 'Right-arm fast'),
    'Ishant Sharma': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Arshad Khan': ('Left Handed Bat', 'Left-arm medium-fast'),
    'Gurnoor Brar': ('Left Handed Bat', 'Right-arm fast-medium'),
    'Ashok Sharma': ('Right Handed Bat', 'Right-arm medium'),
    'Luke Wood': ('Left Handed Bat', 'Left-arm fast-medium'),
    'Prithvi Raj Yarra': ('Right Handed Bat', 'Left-arm fast-medium'),
    'Rishabh Pant': ('Left Handed Bat', 'None'),
    'Nicholas Pooran': ('Left Handed Bat', 'Right-arm offbreak'),
    'Josh Inglis': ('Right Handed Bat', 'None'),
    'Mukul Choudhary': ('Right Handed Bat', 'Right-arm medium'),
    'Aiden Markram': ('Right Handed Bat', 'Right-arm offbreak'),
    'Ayush Badoni': ('Right Handed Bat', 'Right-arm offbreak'),
    'Abdul Samad': ('Right Handed Bat', 'Legbreak'),
    'Matthew Breetzke': ('Right Handed Bat', 'None'),
    'Himmat Singh': ('Right Handed Bat', 'Right-arm offbreak'),
    'Akshat Raghuwanshi': ('Right Handed Bat', 'Right-arm offbreak'),
    'Mitchell Marsh': ('Right Handed Bat', 'Right-arm medium'),
    'Shahbaz Ahamad': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Arshin Kulkarni': ('Right Handed Bat', 'Right-arm medium'),
    'George Linde': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Mohammed Shami': ('Right Handed Bat', 'Right-arm fast'),
    'Mayank Yadav': ('Right Handed Bat', 'Right-arm fast'),
    'Avesh Khan': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Mohsin Khan': ('Left Handed Bat', 'Left-arm medium-fast'),
    'Arjun Tendulkar': ('Left Handed Bat', 'Left-arm medium-fast'),
    'Manimaran Siddharth': ('Right Handed Bat', 'Slow left-arm orthodox'),
    'Prince Yadav': ('Right Handed Bat', 'Right-arm medium'),
    'Anrich Nortje': ('Right Handed Bat', 'Right-arm fast'),
    'Akash Singh': ('Right Handed Bat', 'Left-arm medium-fast'),
    'Digvesh Singh Rathi': ('Right Handed Bat', 'Right-arm medium'),
    'Naman Tiwari': ('Left Handed Bat', 'Left-arm fast-medium'),
    'KL Rahul': ('Right Handed Bat', 'None'),
    'Tristan Stubbs': ('Right Handed Bat', 'Right-arm offbreak'),
    'Abishek Porel': ('Left Handed Bat', 'None'),
    'Ben Duckett': ('Left Handed Bat', 'Right-arm offbreak'),
    'David Miller': ('Left Handed Bat', 'Right-arm offbreak'),
    'Pathum Nissanka': ('Right Handed Bat', 'None'),
    'Prithvi Shaw': ('Right Handed Bat', 'Right-arm offbreak'),
    'Karun Nair': ('Right Handed Bat', 'Right-arm offbreak'),
    'Nitish Rana': ('Left Handed Bat', 'Right-arm offbreak'),
    'Sahil Parakh': ('Left Handed Bat', 'None'),
    'Axar Patel': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Sameer Rizvi': ('Right Handed Bat', 'Right-arm offbreak'),
    'Ashutosh Sharma': ('Right Handed Bat', 'Right-arm medium'),
    'Ajay Mandal': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Kuldeep Yadav': ('Left Handed Bat', 'Left-arm wrist-spin'),
    'Mitchell Starc': ('Left Handed Bat', 'Left-arm fast'),
    'T Natarajan': ('Left Handed Bat', 'Left-arm medium-fast'),
    'Mukesh Kumar': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Dushmantha Chameera': ('Right Handed Bat', 'Right-arm fast'),
    'Lungi Ngidi': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Kyle Jamieson': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Vipraj Nigam': ('Right Handed Bat', 'Legbreak'),
    'Auqib Nabi Dar': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Tripurana Vijay': ('Right Handed Bat', 'Right-arm offbreak'),
    'Madhav Tiwari': ('Right Handed Bat', 'Right-arm medium'),
    'Tim Seifert': ('Right Handed Bat', 'None'),
    'Tejasvi Singh': ('Right Handed Bat', 'Right-arm medium'),
    'Rinku Singh': ('Left Handed Bat', 'Right-arm offbreak'),
    'Manish Pandey': ('Right Handed Bat', 'Right-arm medium'),
    'Rovman Powell': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Rahul Tripathi': ('Right Handed Bat', 'Right-arm medium'),
    'Finn Allen': ('Right Handed Bat', 'None'),
    'Sarthak Ranjan': ('Left Handed Bat', 'Right-arm medium'),
    'Angkrish Raghuvanshi': ('Right Handed Bat', 'Slow left-arm orthodox'),
    'Ajinkya Rahane': ('Right Handed Bat', 'Right-arm medium'),
    'Sunil Narine': ('Left Handed Bat', 'Right-arm offbreak'),
    'Cameron Green': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Rachin Ravindra': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Ramandeep Singh': ('Right Handed Bat', 'Right-arm medium'),
    'Anukul Roy': ('Left Handed Bat', 'Slow left-arm orthodox'),
    'Daksh Kamra': ('Right Handed Bat', 'Right-arm medium'),
    'Varun Chakaravarthy': ('Right Handed Bat', 'Legbreak googly'),
    'Harshit Rana': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Vaibhav Arora': ('Right Handed Bat', 'Right-arm medium-fast'),
    'Matheesha Pathirana': ('Right Handed Bat', 'Right-arm fast'),
    'Umran Malik': ('Right Handed Bat', 'Right-arm fast'),
    'Blessing Muzarabani': ('Right Handed Bat', 'Right-arm fast-medium'),
    'Kartik Tyagi': ('Right Handed Bat', 'Right-arm fast'),
    'Prashant Solanki': ('Right Handed Bat', 'Legbreak googly'),
    'Saurabh Dubey': ('Right Handed Bat', 'Left-arm medium-fast'),
    'Rohit Sharma': ('Right Handed Bat', 'Right-arm offbreak'),
    'Surya Kumar Yadav': ('Right Handed Bat', 'Right-arm medium'),
    'Robin Minz': ('Left Handed Bat', 'None'),
    'Ryan Rickelton': ('Left Handed Bat', 'None'),
    'Tilak Varma': ('Left Handed Bat', 'Right-arm offbreak'),
    'Trent Boult': ('Right Handed Bat', 'Left-arm fast-medium'),
    'Jasprit Bumrah': ('Right Handed Bat', 'Right-arm fast'),
    'Deepak Chahar': ('Right Handed Bat', 'Right-arm medium'),
    'Ashwani Kumar': ('Right Handed Bat', 'Right-arm medium'),
    'Raghu Sharma': ('Right Handed Bat', 'Legbreak googly'),
    'Allah Ghazanfar': ('Right Handed Bat', 'Right-arm offbreak'),
    'Mayank Markande': ('Right Handed Bat', 'Legbreak googly'),
    'Sherfane Rutherford': ('Left Handed Bat', 'Right-arm fast-medium'),
    'Quinton De Kock': ('Left Handed Bat', 'None'),
    'Krish Bhagat': ('Right Handed Bat', 'Right-arm medium'),
    'Mohammad Izhar': ('Right Handed Bat', 'Right-arm medium'),
    'Danish Malewar': ('Right Handed Bat', 'Right-arm medium'),
    'Hardik Pandya': ('Right Handed Bat', 'Right-arm medium-fast')
}

with open('supabase_players.sql', 'r', encoding='utf-8') as f:
    sql_data = f.read()

def replacer(match):
    name = match.group(1)
    if name in data:
        batting, bowling = data[name]
        # match.group(0) is like 'Name', 'Team', 'Role', 50, 'Initials', 'Country', 'City', 'OldBat', 'OldBowl'
        # we only replace the last two strings
        return re.sub(r"'[^']+',\s*'[^']+'$", f"'{batting}', '{bowling}'", match.group(0))
    return match.group(0)

# The pattern needs to match: 'Name', 'Team', 'Role', price, 'Initials', 'Country', 'City', 'Batting', 'Bowling'
# Actually, the format is:
# (1, 'Shreyas Iyer', 'PBKS', 'BATTER', 150, 'SI', 'India', 'Punjab', 'Right Handed Bat', 'Right-arm legbreak',
pattern = re.compile(r"\(\d+,\s*'([^']+)',\s*'[^']+',\s*'[^']+',\s*\d+,\s*'[^']+',\s*'[^']+',\s*'[^']+',\s*'[^']+',\s*'[^']+'")

new_sql = pattern.sub(replacer, sql_data)

with open('supabase_players.sql', 'w', encoding='utf-8') as f:
    f.write(new_sql)

print("Updated batting and bowling styles in supabase_players.sql")
